package carPool.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.joda.time.DateTime;

import carPool.domain.GeoPosition;
import carPool.jaxb.LocalTimeAdapter;

/**
 * <h2>Class to represent a Trip.</h2>
 *
 * <p>
 * An instance of this class represents a DTO Trip. A DTO Trip includes a subset
 * of Trip data, and DTO Trips objects are exchanged between clients and the
 * Trip Web service.
 * </p>
 *
 * <h4>A DTO Trip is described by:</h4>
 * <p>
 * - It's start and end GeoPosition's, the Traveler making the trip (identified
 * by id), and the start time of the Trip;
 * </p>
 *
 * <p>
 * A Trip is uniquely identified by an id value of type long.
 * </p>
 *
 */
@XmlRootElement(name = "Trip")
@XmlAccessorType(XmlAccessType.FIELD)
public class Trip {

	@XmlAttribute(name = "id")
	private long _id;

	@XmlAttribute(name = "traveler-id")
	private long _travelerID;

	@XmlElement(name = "start-time")
	@XmlJavaTypeAdapter(value = LocalTimeAdapter.class)
	private DateTime _startTime;

	@XmlElement(name = "start")
	private GeoPosition _start;

	@XmlElement(name = "end")
	private GeoPosition _end;

	/**
	 * Constructs a DTO Trip instance. This method is intended to be called by
	 * web service clients when creating new Trips. This id field is not
	 * required because it is generated by the web service. Of the constructor's
	 * parameters, all fields must be non-null.
	 *
	 * @param travelerID
	 * @param startTime
	 * @param start
	 * @param end
	 */
	public Trip(long travelerID, DateTime startTime, GeoPosition start, GeoPosition end) {
		_travelerID = travelerID;
		_startTime = startTime;
		_start = start;
		_end = end;
	}

	/**
	 * Constructs a DTO Trip instance. This method should NOT be called by Web
	 * Service clients. It is intended to be used by the Web Service
	 * implementation when creating a DTO Trip from a domain-model Trip object.
	 *
	 * @param id
	 * @param travelerID
	 * @param startTime
	 * @param start
	 * @param end
	 */
	public Trip(long id, long travelerID, DateTime startTime, GeoPosition start, GeoPosition end) {
		_id = id;
		_travelerID = travelerID;
		_startTime = startTime;
		_start = start;
		_end = end;
	}

	public long getID() {
		return _id;
	}

	public void setID(long _id) {
		this._id = _id;
	}

	public long getTravelerID() {
		return _travelerID;
	}

	public void setTravelerID(long _travelerID) {
		this._travelerID = _travelerID;
	}

	public DateTime getStartTime() {
		return _startTime;
	}

	public void setStartTime(DateTime _startTime) {
		this._startTime = _startTime;
	}

	public GeoPosition getStart() {
		return _start;
	}

	public void setStart(GeoPosition _start) {
		this._start = _start;
	}

	public GeoPosition getEnd() {
		return _end;
	}

	public void setEnd(GeoPosition _end) {
		this._end = _end;
	}

	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Trip)) {
			return false;
		}
		if (obj == this) {
			return true;
		}
		Trip t = (Trip) obj;
		return new EqualsBuilder().append(_id, t._id).append(_travelerID, t._travelerID).append(_start, t._startTime)
				.append(_start, t._start).append(_end, t._end).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(17, 31).append(_id).append(_travelerID).append(_start).append(_start).append(_end)
				.toHashCode();
	}
}
